[package]
name = "mirabel_connect_four"
authors = ["vilaureu"]
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["mirabel"]
mirabel = ["dep:mirabel"]

[dependencies.surena_game]
git = "https://github.com/vilaureu/surena_game_rs"
rev = "fc703a3245038014d2d949ef409aac50cdd81027"

[dependencies.mirabel]
git = "https://github.com/vilaureu/mirabel_rs"
rev = "9f35ecb65f557b7eec3b3d230cf83c9db4ba4634"
optional = true

[profile.release]
panic = "abort"
lto = "thin"
strip = true
