[package]
name = "mirabel_connect_four"
authors = ["vilaureu"]
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["mirabel"]
mirabel = ["dep:mirabel"]

[dependencies.surena_game]
git = "https://github.com/vilaureu/surena_game_rs"
rev = "16af08015b27c92b6825886922ffd365f0877ed3"

[dependencies.mirabel]
git = "https://github.com/vilaureu/mirabel_rs"
rev = "b3c55bb5bd409121860c09b9a3419aac8920797f"
optional = true

[profile.release]
panic = "abort"
lto = "thin"
strip = true
