[package]
name = "surena_connect_four"
authors = ["vilaureu"]
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies.surena_game]
git = "https://github.com/vilaureu/surena_game_rs"
rev = "16af08015b27c92b6825886922ffd365f0877ed3"

[profile.release]
panic = "abort"
lto = "thin"
strip = true
