[package]
name = "surena_connect_four"
authors = ["vilaureu"]
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
surena_game = { git = "https://github.com/vilaureu/surena_game_rs", rev = "e4c7f904fa1d6d7da947474bda8dec0d5530ab57" }

[profile.release]
panic = "abort"
lto = "thin"
strip = true
