name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    outputs:
      mirabel_sys: ${{ steps.mirabel_sys.outputs.rev }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ~/.cargo/.*
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: surena_connect_four
          path: target/debug/libsurena_connect_four.so
      - name: Install cargo-lock
        run: cargo install cargo-lock --version=8.0.3 --features=cli
      # find out mirabel_sys commit hash via cargo-lock
      - name: Get mirabel_sys revision
        id: mirabel_sys
        run: >-
          echo "rev=$(cargo lock --sources --package mirabel_sys | sed -rn
          's/^.+rev=([a-f0-9]+)#\1\)$/\1/p')" >> $GITHUB_OUTPUT
      - name: Test
        timeout-minutes: 5
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --no-deps -- --deny=warnings

  surena:
    name: Surena integration test
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vilaureu/mirabel_sys
          ref: ${{ needs.build.outputs.mirabel_sys }}
          submodules: recursive
      - name: Get surena commit
        id: get-surena
        # purge cache on submodule update
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        working-directory: mirabel/lib/surena
      - uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-surena-${{ steps.get-surena.outputs.commit }}
      - uses: actions/download-artifact@v3
        with:
          name: surena_connect_four
      - name: Make libsurena_connect_four.so executable
        run: chmod +x libsurena_connect_four.so
      - name: Configure
        # GCC-9 crashes when compiling surena
        run: >-
          cmake -S mirabel/lib/surena -B build -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=/usr/bin/gcc-10
          -DCMAKE_CXX_COMPILER=/usr/bin/g++-10
      - name: Build
        run: cmake --build build
      - name: Test
        timeout-minutes: 5
        run: >-
          echo -e "0\n1\ninvalid\n1\n10\n2\n2\n3" | ./build/surena
          --game-plugin ./libsurena_connect_four.so --game-options 4x3@3
